### ISSUE TITLE
feat: add stylelint

### ISSUE THREAD

**Issue by corinneling** [corinneling/beginners-guide#2]
#### Description

Add [stylelint](https://www.npmjs.com/package/stylelint) to the project. This article about using [stylelint with sass](https://medium.com/@bjankord/how-to-lint-scss-with-stylelint-dc87809a9878) has helped with setting it up on other projects. 

The stylelint website includes docs on all of [the rules](https://stylelint.io/user-guide/rules/) that can be added to a stylelint config file.

**Comment by yosevukilonzo** [comment]
I claim this! ⚔️
